#!/usr/bin/env python3
"""
Train and evaluate rodent pose heatmaps plus the Pattern-3 distance-to-grab score.

Preferred inputs are the annotation CSVs generated by rodent_dataset.py:

1) Training / validation / test data:
     - generated/rodent_annotations_train.csv
     - generated/rodent_annotations_val.csv
     - generated/rodent_annotations_test.csv

2) Template data:
     - A one-row CSV with the same columns as the generated annotation files.
     - A legacy JSON template record is still accepted.

CSV rows with label=0 or missing required keypoints are filtered out because this
model learns pose heatmaps and a distance target, not a binary classification task.

Examples:
    uv run python swin2_model.py \
        --mode train \
        --train-data generated/rodent_annotations_train.csv \
        --val-data generated/rodent_annotations_val.csv \
        --template-data generated/template.csv \
        --outdir runs/run1

    uv run python swin2_model.py \
        --mode train \
        --train-data generated/rodent_annotations_train.csv \
        --val-data generated/rodent_annotations_val.csv \
        --template-data generated/template.csv \
        --outdir runs/swin2 \
        --backbone swinv2_cr_tiny_384

    uv run python swin2_model.py \
        --mode test \
        --test-data generated/rodent_annotations_test.csv \
        --checkpoint runs/run1/best.pt

Backbone note:
        - `resnet18` keeps the original default learning rate.
        - Non-ResNet backbones such as Swin V2 use a lower default learning rate unless
            `--lr` is provided explicitly.
        - Large-batch Swin2 runs (`--batch_size 48` or higher) auto-enable a cosine
            schedule with warmup unless overridden explicitly.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

from rodent_dataset import BODY_PARTS

# ----------------------------
# Keypoint order (your list)
# ----------------------------
BP = [
    "nose",
    "upper_jaw",
    "lower_jaw",
    "mouth_end_right",
    "mouth_end_left",
    "right_eye",
    "right_earbase",
    "right_earend",
    "right_antler_base",
    "right_antler_end",
    "left_eye",
    "left_earbase",
    "left_earend",
    "left_antler_base",
    "left_antler_end",
    "neck_base",
    "neck_end",
    "throat_base",
    "throat_end",
    "back_base",
    "back_end",
    "back_middle",
    "tail_base",
    "tail_end",
    "front_left_thai",
    "front_left_knee",
    "front_left_paw",
    "front_right_thai",
    "front_right_knee",
    "front_right_paw",
    "back_left_paw",
    "back_left_thai",
    "back_right_thai",
    "back_left_knee",
    "back_right_knee",
    "back_right_paw",
    "belly_bottom",
    "body_middle_right",
    "body_middle_left",
]
IDX = {name: i for i, name in enumerate(BP)}
K = len(BP)

IDX_NOSE = IDX["nose"]
IDX_NECK_BASE = IDX["neck_base"]
IDX_BACK_MID = IDX["back_middle"]

if BODY_PARTS != BP:
    raise ValueError("BODY_PARTS must match swin2_model.BP ordering")

FRONT_SUBSET_NAMES = [
    "neck_base",
    "back_middle",
    "front_left_thai",
    "front_left_knee",
    "front_left_paw",
    "front_right_thai",
    "front_right_knee",
    "front_right_paw",
]
REQUIRED_SAMPLE_NAMES = ["nose", *FRONT_SUBSET_NAMES]


# ----------------------------
# Config
# ----------------------------
@dataclass
class Config:
    image_size: int = 384
    heatmap_size: int = 96
    stride: int = 4  # image_size / heatmap_size
    sigma_px_out: float = 2.5  # gaussian sigma in HEATMAP pixels
    conf_min: float = 0.05

    # Backbone / decoder
    backbone: str = "resnet18"
    backbone_preset: str | None = None
    pretrained: bool = True
    backbone_feature_index: int = 2
    decoder_channels: int = 256

    # Pattern-3 penalties (non-rotation-invariant, smooth L2)
    gamma_orient: float = 0.5
    gamma_dir: float = 2.0
    gamma_rear: float = 1.0
    rear_thresh: float = 0.7
    eps: float = 1e-6

    # Train
    batch_size: int = 16
    lr: float = 3e-4
    weight_decay: float = 1e-4
    epochs: int = 20
    lambda_dist: float = 0.3
    num_workers: int = 4
    scheduler: str | None = None
    warmup_epochs: int = 0
    warmup_start_factor: float = 0.5
    min_lr_ratio: float = 0.1
    early_stop_patience: int | None = None

    # Soft-argmax
    softargmax_beta: float = 50.0

    # Keypoint weights
    paw_w: float = 5.0
    knee_w: float = 2.5
    thai_w: float = 1.5

    device: str = "cuda" if torch.cuda.is_available() else "cpu"


CFG = Config()

BACKBONE_PRESETS: dict[str, dict[str, int]] = {
    "balanced": {
        "backbone_feature_index": 2,
        "decoder_channels": 256,
    },
    "accuracy": {
        "backbone_feature_index": 3,
        "decoder_channels": 256,
    },
}


def default_lr_for_backbone(backbone: str) -> float:
    return 3e-4 if backbone == "resnet18" else 1e-5


def uses_timm_backbone(backbone: str) -> bool:
    return backbone != "resnet18"


def apply_large_batch_training_defaults(
    cfg: Config,
    *,
    user_provided_lr: bool,
    user_provided_scheduler: bool,
    user_provided_warmup_epochs: bool,
    user_provided_warmup_start_factor: bool,
    user_provided_min_lr_ratio: bool,
) -> None:
    if not uses_timm_backbone(cfg.backbone):
        return
    if cfg.batch_size < 48:
        return
    if not user_provided_lr:
        cfg.lr = 2e-5
    if not user_provided_scheduler:
        cfg.scheduler = "cosine"
    if not user_provided_warmup_epochs:
        cfg.warmup_epochs = 2
    if not user_provided_warmup_start_factor:
        cfg.warmup_start_factor = 0.5
    if not user_provided_min_lr_ratio:
        cfg.min_lr_ratio = 0.1


def learning_rate_for_epoch(cfg: Config, epoch: int) -> float:
    if cfg.scheduler is None:
        return cfg.lr

    if cfg.scheduler != "cosine":
        raise ValueError(f"Unsupported scheduler: {cfg.scheduler}")

    if cfg.warmup_epochs > 0 and epoch <= cfg.warmup_epochs:
        if cfg.warmup_epochs == 1:
            return cfg.lr
        progress = (epoch - 1) / max(cfg.warmup_epochs - 1, 1)
        factor = cfg.warmup_start_factor + (1.0 - cfg.warmup_start_factor) * progress
        return cfg.lr * factor

    decay_epochs = max(cfg.epochs - cfg.warmup_epochs, 1)
    decay_span = max(decay_epochs - 1, 1)
    completed_decay_epochs = min(max(epoch - cfg.warmup_epochs - 1, 0), decay_span)
    cosine_progress = completed_decay_epochs / decay_span
    min_lr = cfg.lr * cfg.min_lr_ratio
    cosine_factor = 0.5 * (1.0 + math.cos(math.pi * cosine_progress))
    return min_lr + (cfg.lr - min_lr) * cosine_factor


def set_optimizer_lr(opt: torch.optim.Optimizer, lr: float) -> None:
    for group in opt.param_groups:
        group["lr"] = lr


def scheduler_state_for_checkpoint(
    cfg: Config, epoch: int, lr: float
) -> dict[str, Any] | None:
    if cfg.scheduler is None:
        return None
    return {
        "name": cfg.scheduler,
        "last_epoch": epoch,
        "last_lr": lr,
        "warmup_epochs": cfg.warmup_epochs,
        "warmup_start_factor": cfg.warmup_start_factor,
        "min_lr_ratio": cfg.min_lr_ratio,
    }


def resolve_resume_tensorboard_dir(
    args_tensorboard_dir: str | None,
    outdir: str,
    checkpoint: dict[str, Any] | None,
) -> str | None:
    if args_tensorboard_dir is not None:
        return args_tensorboard_dir
    if checkpoint is None:
        return None
    tensorboard_meta = checkpoint.get("tensorboard")
    if not isinstance(tensorboard_meta, dict):
        return None
    resumed_logdir = tensorboard_meta.get("logdir")
    if not isinstance(resumed_logdir, str):
        return None
    outdir_abs = os.path.abspath(outdir)
    resumed_abs = os.path.abspath(resumed_logdir)
    try:
        common = os.path.commonpath([outdir_abs, resumed_abs])
    except ValueError:
        return None
    if common == outdir_abs:
        return resumed_logdir
    return None


def apply_backbone_preset(cfg: Config, preset: str | None) -> None:
    cfg.backbone_preset = preset
    if preset is None or cfg.backbone == "resnet18":
        return

    values = BACKBONE_PRESETS[preset]
    cfg.backbone_feature_index = values["backbone_feature_index"]
    cfg.decoder_channels = values["decoder_channels"]


def default_tensorboard_dir(outdir: str) -> str:
    return os.path.join(outdir, "tensorboard")


def build_tensorboard_writer(
    outdir: str,
    tensorboard_dir: str | None = None,
) -> tuple[SummaryWriter, str]:
    logdir = tensorboard_dir or default_tensorboard_dir(outdir)
    os.makedirs(logdir, exist_ok=True)
    return SummaryWriter(log_dir=logdir), logdir


def write_metrics_to_tensorboard(
    writer: SummaryWriter,
    epoch: int,
    train_metrics: dict[str, float],
    val_metrics: dict[str, float],
    lr: float,
) -> None:
    writer.add_scalar("loss/train", train_metrics["loss"], epoch)
    writer.add_scalar("loss/val", val_metrics["loss"], epoch)
    writer.add_scalar("loss_hm/train", train_metrics["loss_hm"], epoch)
    writer.add_scalar("loss_hm/val", val_metrics["loss_hm"], epoch)
    writer.add_scalar("loss_dist/train", train_metrics["loss_dist"], epoch)
    writer.add_scalar("loss_dist/val", val_metrics["loss_dist"], epoch)
    writer.add_scalar("kp_error/train", train_metrics["kp_error"], epoch)
    writer.add_scalar("kp_error/val", val_metrics["kp_error"], epoch)
    writer.add_scalar("optimizer/lr", lr, epoch)


def decoded_keypoint_error(
    heatmaps_pred: torch.Tensor,
    heatmaps_target: torch.Tensor,
    conf: torch.Tensor,
    valid: torch.Tensor,
    cfg: Config,
) -> torch.Tensor:
    pred_coords = soft_argmax_2d(heatmaps_pred, beta=cfg.softargmax_beta) * float(
        cfg.stride
    )
    target_coords = soft_argmax_2d(heatmaps_target, beta=cfg.softargmax_beta) * float(
        cfg.stride
    )
    per_keypoint = torch.norm(pred_coords - target_coords, dim=-1)
    weights = conf * valid
    return (weights * per_keypoint).sum() / (weights.sum() + cfg.eps)


def render_keypoints_for_tensorboard(
    image: torch.Tensor,
    coords_hm: torch.Tensor,
    *,
    image_size: int,
    heatmap_size: int,
    color: tuple[float, float, float],
    radius: int = 2,
) -> torch.Tensor:
    canvas = image.detach().float().cpu().clone()
    scale = image_size / float(heatmap_size)
    rgb = torch.tensor(color, dtype=canvas.dtype).view(3, 1, 1)

    for coord in coords_hm:
        if not torch.isfinite(coord).all():
            continue
        x = int(round(float(coord[0].item()) * scale))
        y = int(round(float(coord[1].item()) * scale))
        x = max(0, min(image_size - 1, x))
        y = max(0, min(image_size - 1, y))
        x0 = max(0, x - radius)
        x1 = min(image_size, x + radius + 1)
        y0 = max(0, y - radius)
        y1 = min(image_size, y + radius + 1)
        canvas[:, y0:y1, x0:x1] = rgb

    return canvas.clamp(0.0, 1.0)


def _normalize_heatmap_for_tensorboard(heatmap: torch.Tensor) -> torch.Tensor:
    heatmap = heatmap.detach().float().cpu()
    heatmap = heatmap - heatmap.amin()
    heatmap = heatmap / heatmap.amax().clamp_min(1e-6)
    return torch.stack(
        [heatmap[0], heatmap[0] * 0.4, torch.zeros_like(heatmap[0])], dim=0
    )


def capture_tensorboard_example(
    images: torch.Tensor,
    heatmaps_target: torch.Tensor,
    heatmaps_pred: torch.Tensor,
    image_size: int,
    softargmax_beta: float = 50.0,
) -> dict[str, torch.Tensor]:
    image = images[0].detach().float().cpu().clamp(0.0, 1.0)
    heatmap_size = int(heatmaps_target.shape[-1])
    target_heatmap = heatmaps_target[0].detach().float().cpu().amax(dim=0, keepdim=True)
    pred_heatmap = heatmaps_pred[0].detach().float().cpu().amax(dim=0, keepdim=True)
    target_coords = soft_argmax_2d(heatmaps_target[:1].detach(), beta=softargmax_beta)[
        0
    ].cpu()
    pred_coords = soft_argmax_2d(heatmaps_pred[:1].detach(), beta=softargmax_beta)[
        0
    ].cpu()

    target_heatmap = F.interpolate(
        target_heatmap.unsqueeze(0),
        size=(image_size, image_size),
        mode="bilinear",
        align_corners=False,
    ).squeeze(0)
    pred_heatmap = F.interpolate(
        pred_heatmap.unsqueeze(0),
        size=(image_size, image_size),
        mode="bilinear",
        align_corners=False,
    ).squeeze(0)

    target_rgb = _normalize_heatmap_for_tensorboard(target_heatmap)
    pred_rgb = _normalize_heatmap_for_tensorboard(pred_heatmap)
    target_keypoints = render_keypoints_for_tensorboard(
        image,
        target_coords,
        image_size=image_size,
        heatmap_size=heatmap_size,
        color=(0.0, 1.0, 0.0),
    )
    pred_keypoints = render_keypoints_for_tensorboard(
        image,
        pred_coords,
        image_size=image_size,
        heatmap_size=heatmap_size,
        color=(1.0, 0.2, 0.2),
    )
    combined_keypoints = render_keypoints_for_tensorboard(
        target_keypoints,
        pred_coords,
        image_size=image_size,
        heatmap_size=heatmap_size,
        color=(1.0, 0.2, 0.2),
    )
    return {
        "image": image,
        "target_heatmap": target_rgb,
        "pred_heatmap": pred_rgb,
        "target_overlay": torch.clamp(0.7 * image + 0.5 * target_rgb, 0.0, 1.0),
        "pred_overlay": torch.clamp(0.7 * image + 0.5 * pred_rgb, 0.0, 1.0),
        "target_keypoints": target_keypoints,
        "pred_keypoints": pred_keypoints,
        "combined_keypoints": combined_keypoints,
    }


def write_example_artifacts_to_tensorboard(
    writer: SummaryWriter,
    epoch: int,
    split_name: str,
    example: dict[str, torch.Tensor] | None,
) -> None:
    if example is None:
        return

    writer.add_image(f"examples/{split_name}/image", example["image"], epoch)
    writer.add_image(
        f"examples/{split_name}/target_heatmap", example["target_heatmap"], epoch
    )
    writer.add_image(
        f"examples/{split_name}/pred_heatmap", example["pred_heatmap"], epoch
    )
    writer.add_image(
        f"examples/{split_name}/target_overlay", example["target_overlay"], epoch
    )
    writer.add_image(
        f"examples/{split_name}/pred_overlay", example["pred_overlay"], epoch
    )
    writer.add_image(
        f"examples/{split_name}/target_keypoints", example["target_keypoints"], epoch
    )
    writer.add_image(
        f"examples/{split_name}/pred_keypoints", example["pred_keypoints"], epoch
    )
    writer.add_image(
        f"examples/{split_name}/combined_keypoints",
        example["combined_keypoints"],
        epoch,
    )


# ----------------------------
# Parse your frame-level DLC record
# ----------------------------
def extract_xy_conf_from_record(
    record: Dict[str, Any],
) -> tuple[np.ndarray, np.ndarray]:
    """
    record["bodyparts"][0] is a list of length K of [x,y,conf].
    Returns:
      xy: (K,2) float32
      cf: (K,) float32
    """
    pts = record["bodyparts"][0]
    arr = np.asarray(pts, dtype=np.float32)  # (K,3)
    if arr.shape[0] != K:
        raise ValueError(f"Expected K={K} keypoints, got {arr.shape[0]}")
    xy = arr[:, :2].copy()
    cf = arr[:, 2].copy()
    return xy, cf


# ----------------------------
# Heatmap utils
# ----------------------------
def gaussian_2d(
    height: int, width: int, cx: float, cy: float, sigma: float, device
) -> torch.Tensor:
    yy = torch.arange(height, device=device).float().view(-1, 1)
    xx = torch.arange(width, device=device).float().view(1, -1)
    return torch.exp(-((xx - cx) ** 2 + (yy - cy) ** 2) / (2.0 * sigma * sigma))


def make_heatmaps(
    keypoints_xy: torch.Tensor,  # (K,2) in resized image coords
    valid: torch.Tensor,  # (K,) bool
    out_h: int,
    out_w: int,
    in_h: int,
    in_w: int,
    sigma_px_out: float,
) -> torch.Tensor:
    device = keypoints_xy.device
    heatmaps = torch.zeros((keypoints_xy.shape[0], out_h, out_w), device=device)

    sx = out_w / float(in_w)
    sy = out_h / float(in_h)

    for k in range(keypoints_xy.shape[0]):
        if not bool(valid[k]):
            continue
        x, y = keypoints_xy[k]
        cx = (x * sx).float()
        cy = (y * sy).float()
        if cx < 0 or cy < 0 or cx >= out_w or cy >= out_h:
            continue
        heatmaps[k] = gaussian_2d(
            out_h, out_w, float(cx), float(cy), sigma_px_out, device
        )

    return heatmaps


# ----------------------------
# Soft-argmax (differentiable keypoint decoding)
# ----------------------------
def soft_argmax_2d(heatmaps: torch.Tensor, beta: float = 50.0) -> torch.Tensor:
    """
    heatmaps: (B,K,H,W) logits
    returns:  (B,K,2) in heatmap pixel coords (x,y)
    """
    B, K_, H, W = heatmaps.shape
    h = heatmaps.reshape(B, K_, H * W)
    p = F.softmax(h * beta, dim=-1)

    xs = torch.linspace(0, W - 1, W, device=heatmaps.device)
    ys = torch.linspace(0, H - 1, H, device=heatmaps.device)
    yy, xx = torch.meshgrid(ys, xs, indexing="ij")
    grid = torch.stack([xx.reshape(-1), yy.reshape(-1)], dim=-1)  # (HW,2)

    coords = torch.einsum("bkh,hd->bkd", p, grid)
    return coords


# ----------------------------
# Template normalization
# ----------------------------
def normalize_template_neck_backmid(
    T_xy_resized: torch.Tensor, eps: float = 1e-6
) -> torch.Tensor:
    """
    T_xy_resized: (K,2) in resized (384-space) coords
    returns Tn: (K,2) centered at neck_base, scaled by ||back_mid - neck_base||
    """
    sh = T_xy_resized[IDX_NECK_BASE]
    scale = torch.norm(T_xy_resized[IDX_BACK_MID] - sh) + eps
    return (T_xy_resized - sh[None, :]) / scale


# ----------------------------
# Pattern-3 target metric (orientation-aware, smooth L2, NOT rotation-invariant)
# ----------------------------
def grab_distance_target(
    X_xy_resized: torch.Tensor,  # (K,2) in resized coords (384-space)
    conf: torch.Tensor,  # (K,)
    Tn: torch.Tensor,  # (K,2) normalized template
    subset_mask: torch.Tensor,  # (K,) bool
    kp_weight: torch.Tensor,  # (K,)
    cfg: Config,
) -> torch.Tensor:
    valid = subset_mask & (conf >= cfg.conf_min)
    w = kp_weight * conf * valid.float()

    sh = X_xy_resized[IDX_NECK_BASE]
    back_mid = X_xy_resized[IDX_BACK_MID]
    nose = X_xy_resized[IDX_NOSE]

    Xc = X_xy_resized - sh[None, :]
    scale = torch.norm(back_mid - sh) + cfg.eps
    Xn = Xc / scale

    diff = Xn - Tn
    per_k = (diff**2).sum(dim=1)
    d_shape = torch.sqrt((w * per_k).sum() / (w.sum() + cfg.eps))

    # Smooth L2 horizontal penalty from torso axis back_mid - neck_base
    v_orient = (back_mid - sh) / (scale + cfg.eps)
    d_horiz = torch.sqrt((v_orient[1] ** 2) / (v_orient[0] ** 2 + cfg.eps))

    # Direction: require nose left of body => (back_mid - nose).x > 0
    v_dir = (back_mid - nose) / (scale + cfg.eps)
    d_dir = F.relu(-v_dir[0])

    # Rearing proxy: nose->neck_base verticality
    v2 = (sh - nose) / (scale + cfg.eps)
    rear_proxy = torch.sqrt((v2[1] ** 2) / (v2[0] ** 2 + cfg.eps))
    d_rear = F.relu(rear_proxy - cfg.rear_thresh)

    return (
        d_shape
        + cfg.gamma_orient * d_horiz
        + cfg.gamma_dir * d_dir
        + cfg.gamma_rear * d_rear
    )


# ----------------------------
# Losses
# ----------------------------
class WeightedHeatmapMSE(nn.Module):
    kp_w: torch.Tensor

    def __init__(self, kp_weight: torch.Tensor, eps: float = 1e-8):
        super().__init__()
        self.register_buffer("kp_w", kp_weight.float())
        self.eps = eps

    def forward(
        self,
        pred: torch.Tensor,
        target: torch.Tensor,
        conf: torch.Tensor,
        valid: torch.Tensor,
    ) -> torch.Tensor:
        """
        pred/target: (B,K,H,W)
        conf: (B,K)
        valid: (B,K) float {0,1}
        """
        w = self.kp_w[None, :] * conf * valid
        mse = (pred - target) ** 2
        mse = mse.mean(dim=(2, 3))
        return (w * mse).sum() / (w.sum() + self.eps)


# ----------------------------
# Pose model (heatmaps)
# ----------------------------
class SimpleUpsampleHead(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_keypoints: int,
        out_size: int,
        out_channels: int = 256,
    ):
        super().__init__()
        self.out_size = out_size
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, num_keypoints, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        heatmaps = self.block(x)
        if heatmaps.shape[-2:] != (self.out_size, self.out_size):
            heatmaps = F.interpolate(
                heatmaps,
                size=(self.out_size, self.out_size),
                mode="bilinear",
                align_corners=False,
            )
        return heatmaps


class ImageNetInputNormalizer(nn.Module):
    mean: torch.Tensor
    std: torch.Tensor

    def __init__(self):
        super().__init__()
        self.register_buffer(
            "mean", torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)
        )
        self.register_buffer(
            "std", torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)
        )

    def forward(self, images: torch.Tensor) -> torch.Tensor:
        return (images - self.mean) / self.std


class PoseNetResNet(nn.Module):
    """
    Input: (B,3,384,384) -> heatmaps: (B,K,96,96)
    """

    def __init__(
        self,
        num_keypoints: int,
        heatmap_size: int,
        decoder_channels: int,
        pretrained: bool,
    ):
        super().__init__()
        weights = (
            torchvision.models.ResNet18_Weights.IMAGENET1K_V1 if pretrained else None
        )
        backbone = torchvision.models.resnet18(weights=weights)
        self.normalizer = ImageNetInputNormalizer()
        self.stem = nn.Sequential(
            backbone.conv1,
            backbone.bn1,
            backbone.relu,
            backbone.maxpool,
            backbone.layer1,
            backbone.layer2,
            backbone.layer3,
        )
        self.head = SimpleUpsampleHead(
            in_channels=256,
            num_keypoints=num_keypoints,
            out_size=heatmap_size,
            out_channels=decoder_channels,
        )

    def forward(self, images: torch.Tensor) -> torch.Tensor:
        feat = self.stem(self.normalizer(images))
        return self.head(feat)


class PoseNetTimm(nn.Module):
    def __init__(
        self,
        backbone_name: str,
        num_keypoints: int,
        heatmap_size: int,
        decoder_channels: int,
        pretrained: bool,
        feature_index: int,
    ):
        super().__init__()
        self.normalizer = ImageNetInputNormalizer()
        self.backbone = timm.create_model(
            backbone_name,
            pretrained=pretrained,
            features_only=True,
            out_indices=(feature_index,),
        )
        self.backbone_out_channels = int(self.backbone.feature_info.channels()[0])  # type: ignore
        self.head = SimpleUpsampleHead(
            in_channels=self.backbone_out_channels,
            num_keypoints=num_keypoints,
            out_size=heatmap_size,
            out_channels=decoder_channels,
        )

    def forward(self, images: torch.Tensor) -> torch.Tensor:
        feat = self.backbone(self.normalizer(images))[0]
        if feat.ndim != 4:
            raise ValueError(
                f"Expected a 4D feature map from timm backbone, got {feat.shape}"
            )
        if (
            feat.shape[1] != self.backbone_out_channels
            and feat.shape[-1] == self.backbone_out_channels
        ):
            feat = feat.permute(0, 3, 1, 2).contiguous()
        return self.head(feat)


def build_pose_model(cfg: Config, num_keypoints: int) -> nn.Module:
    if cfg.backbone == "resnet18":
        return PoseNetResNet(
            num_keypoints=num_keypoints,
            heatmap_size=cfg.heatmap_size,
            decoder_channels=cfg.decoder_channels,
            pretrained=cfg.pretrained,
        )

    return PoseNetTimm(
        backbone_name=cfg.backbone,
        num_keypoints=num_keypoints,
        heatmap_size=cfg.heatmap_size,
        decoder_channels=cfg.decoder_channels,
        pretrained=cfg.pretrained,
        feature_index=cfg.backbone_feature_index,
    )


# ----------------------------
# Exact-metric Pattern-3 head (from predicted heatmaps)
# ----------------------------
class ExactMetricDistanceHead(nn.Module):
    """
    Decodes keypoints via soft-argmax and computes:
      d_hat = shape_to_template(Xn,Tn) + penalties

    IMPORTANT:
    - This head uses fixed weights (subset + kp_weight) and does not use DLC conf at inference.
    """

    subset_mask: torch.Tensor
    kp_weight: torch.Tensor
    Tn: torch.Tensor

    def __init__(
        self,
        template_Tn: torch.Tensor,
        subset_mask: torch.Tensor,
        kp_weight: torch.Tensor,
        cfg: Config,
    ):
        super().__init__()
        self.cfg = cfg
        self.register_buffer("Tn", template_Tn.float())
        self.register_buffer("subset_mask", subset_mask.bool())
        self.register_buffer("kp_weight", kp_weight.float())

    def forward(self, heatmaps: torch.Tensor) -> tuple[torch.Tensor, dict]:
        cfg = self.cfg
        B, K_, H, W = heatmaps.shape
        assert K_ == K and H == cfg.heatmap_size and W == cfg.heatmap_size

        # Decode in heatmap coords, then scale to resized-image coords (384-space)
        coords_hm = soft_argmax_2d(heatmaps, beta=cfg.softargmax_beta)  # (B,K,2)
        coords = coords_hm * float(cfg.stride)  # (B,K,2)

        sh = coords[:, IDX_NECK_BASE, :]
        back_mid = coords[:, IDX_BACK_MID, :]
        nose = coords[:, IDX_NOSE, :]

        Xc = coords - sh[:, None, :]
        scale = torch.norm(back_mid - sh, dim=-1) + cfg.eps
        Xn = Xc / scale[:, None, None]

        # shape distance on subset
        mask = self.subset_mask[None, :].float()
        w = self.kp_weight[None, :] * mask

        diff = Xn - self.Tn[None, :, :]
        per_k = (diff**2).sum(dim=-1)
        d_shape = torch.sqrt((w * per_k).sum(dim=1) / (w.sum(dim=1) + cfg.eps))

        # smooth L2 horiz penalty on torso axis
        v_orient = (back_mid - sh) / (scale[:, None] + cfg.eps)
        d_horiz = torch.sqrt((v_orient[:, 1] ** 2) / (v_orient[:, 0] ** 2 + cfg.eps))

        # direction
        v_dir = (back_mid - nose) / (scale[:, None] + cfg.eps)
        d_dir = F.relu(-v_dir[:, 0])

        # rearing proxy
        v2 = (sh - nose) / (scale[:, None] + cfg.eps)
        rear_proxy = torch.sqrt((v2[:, 1] ** 2) / (v2[:, 0] ** 2 + cfg.eps))
        d_rear = F.relu(rear_proxy - cfg.rear_thresh)

        d_hat = (
            d_shape
            + cfg.gamma_orient * d_horiz
            + cfg.gamma_dir * d_dir
            + cfg.gamma_rear * d_rear
        )

        dbg = {
            "d_shape": d_shape.detach(),
            "d_horiz": d_horiz.detach(),
            "d_dir": d_dir.detach(),
            "rear_proxy": rear_proxy.detach(),
            "d_rear": d_rear.detach(),
        }
        return d_hat, dbg


# ----------------------------
# Dataset
# ----------------------------
@dataclass
class FrameItem:
    image_path: str
    xy: np.ndarray  # (K,2) original pixels
    conf: np.ndarray  # (K,) in [0,1]


@dataclass
class FrameLoadSummary:
    source_path: str
    total_rows: int
    kept_rows: int
    skipped_negative: int = 0
    skipped_missing_required: int = 0


def _coordinate_column(body_part: str, axis: str) -> str:
    return f"{body_part}_{axis}"


def _resolve_image_path(image_path: str, image_root: Path | None = None) -> str:
    path = Path(image_path)
    if path.is_absolute():
        return str(path)
    root = image_root if image_root is not None else Path.cwd()
    return str((root / path).resolve())


def _row_has_coordinates(row: pd.Series, body_part: str) -> bool:
    x_value = row.get(_coordinate_column(body_part, "x"))
    y_value = row.get(_coordinate_column(body_part, "y"))
    return pd.notna(x_value) and pd.notna(y_value)


def _required_body_parts_present(
    row: pd.Series, required_body_parts: list[str]
) -> bool:
    return all(
        _row_has_coordinates(row, body_part) for body_part in required_body_parts
    )


def _frame_item_from_annotation_row(
    row: pd.Series,
    *,
    image_root: Path | None = None,
) -> FrameItem:
    xy = np.zeros((K, 2), dtype=np.float32)
    conf = np.zeros(K, dtype=np.float32)

    for index, body_part in enumerate(BP):
        x_value = row.get(_coordinate_column(body_part, "x"))
        y_value = row.get(_coordinate_column(body_part, "y"))
        if pd.isna(x_value) or pd.isna(y_value):
            continue
        xy[index, 0] = float(x_value)
        xy[index, 1] = float(y_value)
        conf[index] = 1.0

    return FrameItem(
        image_path=_resolve_image_path(str(row["image_path"]), image_root=image_root),
        xy=xy,
        conf=conf,
    )


def _load_frame_items_from_annotation_csv(
    csv_path: str | Path,
    *,
    image_root: Path | None = None,
    required_body_parts: list[str] | None = None,
    return_summary: bool = False,
) -> List[FrameItem] | tuple[List[FrameItem], FrameLoadSummary]:
    csv_path = Path(csv_path)
    annotations = pd.read_csv(csv_path)
    resolved_image_root = image_root if image_root is not None else csv_path.parent
    required = required_body_parts or REQUIRED_SAMPLE_NAMES

    items: List[FrameItem] = []
    skipped_negative = 0
    skipped_missing_required = 0
    for _, row in annotations.iterrows():
        if int(row.get("label", 0)) != 1:
            skipped_negative += 1
            continue
        if not _required_body_parts_present(row, required):
            skipped_missing_required += 1
            continue
        items.append(
            _frame_item_from_annotation_row(row, image_root=resolved_image_root)
        )

    if not return_summary:
        return items

    return items, FrameLoadSummary(
        source_path=str(csv_path),
        total_rows=len(annotations),
        kept_rows=len(items),
        skipped_negative=skipped_negative,
        skipped_missing_required=skipped_missing_required,
    )


def _load_template_from_annotation_csv(
    template_csv: str | Path,
    *,
    image_root: Path | None = None,
    required_body_parts: list[str] | None = None,
) -> FrameItem:
    template_csv = Path(template_csv)
    annotations = pd.read_csv(template_csv)
    resolved_image_root = image_root if image_root is not None else template_csv.parent
    if len(annotations) != 1:
        raise ValueError("template CSV must contain exactly 1 row")

    row = annotations.iloc[0]
    required = required_body_parts or FRONT_SUBSET_NAMES
    if not _required_body_parts_present(row, required):
        missing = [
            body_part
            for body_part in required
            if not _row_has_coordinates(row, body_part)
        ]
        raise ValueError(
            "template CSV row is missing required keypoints: " + ", ".join(missing)
        )

    return _frame_item_from_annotation_row(row, image_root=resolved_image_root)


class RodentPoseDataset(Dataset):
    """
    - Loads image, resizes to 384x384
    - Scales DLC keypoints from original pixels to resized pixels
    - Builds heatmap targets and Pattern-3 y distance target
    """

    def __init__(
        self,
        items: List[FrameItem],
        template_Tn: torch.Tensor,
        subset_mask: torch.Tensor,
        kp_weight: torch.Tensor,
        cfg: Config,
    ):
        self.items = items
        self.template_Tn = template_Tn.detach().cpu()
        self.subset_mask = subset_mask.detach().cpu()
        self.kp_weight = kp_weight.detach().cpu()
        self.cfg = cfg

    def __len__(self) -> int:
        return len(self.items)

    def __getitem__(self, idx: int) -> dict:
        cfg = self.cfg
        it = self.items[idx]

        img = Image.open(it.image_path).convert("RGB")
        ow, oh = img.size  # W,H in original pixels

        img_rs = img.resize(
            (cfg.image_size, cfg.image_size), resample=Image.Resampling.BILINEAR
        )

        # scale keypoints to resized space
        xy = torch.tensor(it.xy, dtype=torch.float32)  # (K,2) original
        conf = torch.tensor(it.conf, dtype=torch.float32)  # (K,)
        sx = cfg.image_size / float(ow)
        sy = cfg.image_size / float(oh)
        xy_rs = xy.clone()
        xy_rs[:, 0] *= sx
        xy_rs[:, 1] *= sy

        valid = conf >= cfg.conf_min

        heatmaps = make_heatmaps(
            keypoints_xy=xy_rs,
            valid=valid,
            out_h=cfg.heatmap_size,
            out_w=cfg.heatmap_size,
            in_h=cfg.image_size,
            in_w=cfg.image_size,
            sigma_px_out=cfg.sigma_px_out,
        )

        # Pattern-3 target from DLC keypoints (resized space)
        y = grab_distance_target(
            X_xy_resized=xy_rs,
            conf=conf,
            Tn=self.template_Tn,
            subset_mask=self.subset_mask,
            kp_weight=self.kp_weight,
            cfg=cfg,
        )

        x = (
            torch.from_numpy(np.array(img_rs)).permute(2, 0, 1).float() / 255.0
        )  # (3,384,384)

        return {
            "image": x,
            "heatmaps": heatmaps,  # (K,96,96)
            "conf": conf,  # (K,)
            "valid": valid.float(),  # (K,)
            "y": y.float(),  # scalar
        }


# ----------------------------
# Build subset mask + weights (front constellation)
# ----------------------------
def build_subset_and_weights(cfg: Config) -> tuple[torch.Tensor, torch.Tensor]:
    subset_mask = torch.zeros(K, dtype=torch.bool)
    for name in FRONT_SUBSET_NAMES:
        subset_mask[IDX[name]] = True

    kp_weight = torch.ones(K)
    kp_weight[IDX["front_left_paw"]] = cfg.paw_w
    kp_weight[IDX["front_right_paw"]] = cfg.paw_w
    kp_weight[IDX["front_left_knee"]] = cfg.knee_w
    kp_weight[IDX["front_right_knee"]] = cfg.knee_w
    kp_weight[IDX["front_left_thai"]] = cfg.thai_w
    kp_weight[IDX["front_right_thai"]] = cfg.thai_w
    return subset_mask, kp_weight


# ----------------------------
# Load data from your JSON
# ----------------------------
def load_frame_items(json_path: str) -> List[FrameItem]:
    if Path(json_path).suffix.lower() == ".csv":
        return _load_frame_items_from_annotation_csv(json_path)  # type: ignore

    data = json.loads(Path(json_path).read_text())
    if isinstance(data, dict):
        # allow single-record dict
        data = [data]
    items: List[FrameItem] = []
    for rec in data:
        img_path = rec["image_path"]
        xy, cf = extract_xy_conf_from_record(rec)  # (K,2), (K,)
        items.append(FrameItem(image_path=img_path, xy=xy, conf=cf))
    return items


def load_frame_items_with_summary(
    data_path: str,
) -> tuple[List[FrameItem], FrameLoadSummary | None]:
    if Path(data_path).suffix.lower() == ".csv":
        return _load_frame_items_from_annotation_csv(data_path, return_summary=True)  # type: ignore
    return load_frame_items(data_path), None


def load_template_Tn(template_json: str, cfg: Config) -> torch.Tensor:
    """
    Loads template record, scales template keypoints (original pixels -> resized 384-space),
    then normalizes to Tn (center neck_base, scale by neck_base->back_middle).
    """
    if Path(template_json).suffix.lower() == ".csv":
        template = _load_template_from_annotation_csv(template_json)
        img_path = template.image_path
        xy = template.xy
    else:
        rec = json.loads(Path(template_json).read_text())
        if isinstance(rec, list):
            if len(rec) != 1:
                raise ValueError("template_json as list must contain exactly 1 record")
            rec = rec[0]

        img_path = rec["image_path"]
        xy, _cf = extract_xy_conf_from_record(rec)  # xy is original pixels

    img = Image.open(img_path).convert("RGB")
    ow, oh = img.size

    sx = cfg.image_size / float(ow)
    sy = cfg.image_size / float(oh)
    xy_rs = torch.tensor(xy, dtype=torch.float32)
    xy_rs[:, 0] *= sx
    xy_rs[:, 1] *= sy

    Tn = normalize_template_neck_backmid(xy_rs, eps=cfg.eps)
    return Tn


def build_loader(
    items: List[FrameItem],
    template_Tn: torch.Tensor,
    subset_mask: torch.Tensor,
    kp_weight: torch.Tensor,
    cfg: Config,
    *,
    shuffle: bool,
    drop_last: bool,
) -> DataLoader:
    dataset = RodentPoseDataset(items, template_Tn, subset_mask, kp_weight, cfg)
    return DataLoader(
        dataset,
        batch_size=cfg.batch_size,
        shuffle=shuffle,
        num_workers=cfg.num_workers,
        pin_memory=(cfg.device == "cuda"),
        drop_last=drop_last,
    )


def build_runtime_components(
    cfg: Config,
    template_Tn: torch.Tensor,
    subset_mask: torch.Tensor,
    kp_weight: torch.Tensor,
) -> tuple[nn.Module, nn.Module, nn.Module, nn.Module]:
    model = build_pose_model(cfg, num_keypoints=K).to(cfg.device)
    dist_head = ExactMetricDistanceHead(template_Tn, subset_mask, kp_weight, cfg).to(
        cfg.device
    )
    loss_hm = WeightedHeatmapMSE(kp_weight).to(cfg.device)
    loss_dist = nn.SmoothL1Loss(beta=0.5)
    return model, dist_head, loss_hm, loss_dist


def config_from_args(
    *,
    base_cfg: Config | None = None,
    epochs: int | None = None,
    batch_size: int | None = None,
    lr: float | None = None,
    num_workers: int | None = None,
    scheduler: str | None = None,
    warmup_epochs: int | None = None,
    warmup_start_factor: float | None = None,
    min_lr_ratio: float | None = None,
    early_stop_patience: int | None = None,
    backbone: str | None = None,
    backbone_preset: str | None = None,
    pretrained: bool | None = None,
    backbone_feature_index: int | None = None,
    decoder_channels: int | None = None,
) -> Config:
    scheduler_was_explicitly_set = scheduler is not None
    scheduler_was_explicitly_disabled = scheduler == "none"
    if scheduler == "none":
        scheduler = None
    cfg = Config(**(base_cfg.__dict__ if base_cfg is not None else Config().__dict__))
    has_base_cfg = base_cfg is not None
    if epochs is not None:
        cfg.epochs = epochs
    if batch_size is not None:
        cfg.batch_size = batch_size
    if num_workers is not None:
        cfg.num_workers = num_workers
    if scheduler_was_explicitly_disabled:
        cfg.scheduler = None
    elif scheduler is not None:
        cfg.scheduler = scheduler
    if warmup_epochs is not None:
        cfg.warmup_epochs = warmup_epochs
    if warmup_start_factor is not None:
        cfg.warmup_start_factor = warmup_start_factor
    if min_lr_ratio is not None:
        cfg.min_lr_ratio = min_lr_ratio
    if early_stop_patience is not None:
        cfg.early_stop_patience = early_stop_patience
    if backbone is not None:
        cfg.backbone = backbone
    if backbone_preset is not None:
        cfg.backbone_preset = backbone_preset
    apply_backbone_preset(cfg, cfg.backbone_preset)
    if pretrained is not None:
        cfg.pretrained = pretrained
    if backbone_feature_index is not None:
        cfg.backbone_feature_index = backbone_feature_index
    if decoder_channels is not None:
        cfg.decoder_channels = decoder_channels
    user_provided_lr = lr is not None
    if lr is not None:
        cfg.lr = lr
    elif not has_base_cfg:
        cfg.lr = default_lr_for_backbone(cfg.backbone)
        apply_large_batch_training_defaults(
            cfg,
            user_provided_lr=user_provided_lr,
            user_provided_scheduler=scheduler_was_explicitly_set,
            user_provided_warmup_epochs=warmup_epochs is not None,
            user_provided_warmup_start_factor=warmup_start_factor is not None,
            user_provided_min_lr_ratio=min_lr_ratio is not None,
        )
    cfg.device = "cuda" if torch.cuda.is_available() else "cpu"
    return cfg


def config_from_checkpoint_dict(cfg_dict: dict[str, Any]) -> Config:
    defaults = Config()
    values = defaults.__dict__.copy()
    for key, value in cfg_dict.items():
        if key in values:
            values[key] = value
    return Config(**values)


def load_checkpoint_runtime(
    checkpoint_path: str,
    *,
    batch_size: int | None = None,
    num_workers: int | None = None,
) -> tuple[dict[str, Any], Config, nn.Module, nn.Module, nn.Module, nn.Module]:
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    cfg = config_from_args(
        base_cfg=config_from_checkpoint_dict(checkpoint["cfg"]),
        batch_size=batch_size,
        num_workers=num_workers,
        pretrained=False,
    )

    template_Tn = checkpoint["template_Tn"].float().to(cfg.device)
    subset_mask = checkpoint["subset_mask"].bool().to(cfg.device)
    kp_weight = checkpoint["kp_weight"].float().to(cfg.device)
    model, dist_head, loss_hm, loss_dist = build_runtime_components(
        cfg, template_Tn, subset_mask, kp_weight
    )
    model.load_state_dict(checkpoint["model"])
    dist_head.load_state_dict(checkpoint["dist_head"])
    return checkpoint, cfg, model, dist_head, loss_hm, loss_dist


def load_checkpoint_training_runtime(
    checkpoint_path: str,
    *,
    epochs: int | None = None,
    batch_size: int | None = None,
    lr: float | None = None,
    num_workers: int | None = None,
    scheduler: str | None = None,
    warmup_epochs: int | None = None,
    warmup_start_factor: float | None = None,
    min_lr_ratio: float | None = None,
    early_stop_patience: int | None = None,
    backbone: str | None = None,
    backbone_preset: str | None = None,
    pretrained: bool | None = None,
    backbone_feature_index: int | None = None,
    decoder_channels: int | None = None,
) -> tuple[
    dict[str, Any],
    Config,
    nn.Module,
    nn.Module,
    nn.Module,
    nn.Module,
    torch.optim.Optimizer,
]:
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    cfg = config_from_args(
        base_cfg=config_from_checkpoint_dict(checkpoint["cfg"]),
        epochs=epochs,
        batch_size=batch_size,
        lr=lr,
        num_workers=num_workers,
        scheduler=scheduler,
        warmup_epochs=warmup_epochs,
        warmup_start_factor=warmup_start_factor,
        min_lr_ratio=min_lr_ratio,
        early_stop_patience=early_stop_patience,
        backbone=backbone,
        backbone_preset=backbone_preset,
        pretrained=pretrained,
        backbone_feature_index=backbone_feature_index,
        decoder_channels=decoder_channels,
    )

    template_Tn = checkpoint["template_Tn"].float().to(cfg.device)
    subset_mask = checkpoint["subset_mask"].bool().to(cfg.device)
    kp_weight = checkpoint["kp_weight"].float().to(cfg.device)
    model, dist_head, loss_hm, loss_dist = build_runtime_components(
        cfg, template_Tn, subset_mask, kp_weight
    )
    model.load_state_dict(checkpoint["model"])
    dist_head.load_state_dict(checkpoint["dist_head"])

    opt = torch.optim.AdamW(
        list(model.parameters()) + list(dist_head.parameters()),
        lr=cfg.lr,
        weight_decay=cfg.weight_decay,
    )
    if "opt" in checkpoint:
        opt.load_state_dict(checkpoint["opt"])
        if lr is not None:
            set_optimizer_lr(opt, cfg.lr)
        else:
            scheduler_state = checkpoint.get("scheduler")
            if isinstance(scheduler_state, dict):
                last_lr = scheduler_state.get("last_lr")
                if isinstance(last_lr, (int, float)):
                    set_optimizer_lr(opt, float(last_lr))

    return checkpoint, cfg, model, dist_head, loss_hm, loss_dist, opt


def print_frame_summary(split_name: str, summary: FrameLoadSummary | None) -> None:
    if summary is None:
        return
    print(
        f"{split_name}: kept {summary.kept_rows}/{summary.total_rows} rows from {summary.source_path} "
        f"(skipped_negative={summary.skipped_negative}, "
        f"skipped_missing_required={summary.skipped_missing_required})"
    )


def format_checkpoint_provenance(
    checkpoint: dict[str, Any], checkpoint_path: str | None = None
) -> str | None:
    cfg = checkpoint.get("cfg")
    if not isinstance(cfg, dict):
        cfg = {}
    train_run = checkpoint.get("train_run")
    if not isinstance(train_run, dict):
        train_run = {}

    parts: list[str] = []
    if checkpoint_path:
        parts.append(f"checkpoint={checkpoint_path}")
    epoch = checkpoint.get("epoch")
    if isinstance(epoch, int):
        parts.append(f"epoch={epoch:03d}")
    backbone = cfg.get("backbone", "resnet18")
    if isinstance(backbone, str):
        parts.append(f"backbone={backbone}")
    preset = cfg.get("backbone_preset")
    if isinstance(preset, str) and preset:
        parts.append(f"preset={preset}")
    scheduler = cfg.get("scheduler")
    if isinstance(scheduler, str) and scheduler:
        parts.append(f"scheduler={scheduler}")
    best_val_loss = checkpoint.get("best_val_loss", checkpoint.get("val_loss"))
    if isinstance(best_val_loss, (int, float)):
        parts.append(f"best_val_loss={float(best_val_loss):.4f}")
    best_val_kp_error = checkpoint.get(
        "best_val_kp_error", checkpoint.get("val_kp_error")
    )
    if isinstance(best_val_kp_error, (int, float)):
        parts.append(f"best_val_kp_error={float(best_val_kp_error):.4f}")
    outdir = train_run.get("outdir")
    if isinstance(outdir, str) and outdir:
        parts.append(f"run={outdir}")
    resume_checkpoint = train_run.get("resume_checkpoint")
    if isinstance(resume_checkpoint, str) and resume_checkpoint:
        parts.append(f"resumed_from={resume_checkpoint}")
    tensorboard_meta = checkpoint.get("tensorboard")
    if isinstance(tensorboard_meta, dict):
        logdir = tensorboard_meta.get("logdir")
        if isinstance(logdir, str) and logdir:
            parts.append(f"tensorboard={logdir}")

    if not parts:
        return None
    return "checkpoint provenance: " + " | ".join(parts)


def format_eval_metadata(
    checkpoint: dict[str, Any],
    *,
    checkpoint_path: str | None = None,
    test_data: str | None = None,
    cfg: Config | None = None,
) -> str | None:
    cfg_dict = checkpoint.get("cfg")
    if not isinstance(cfg_dict, dict):
        cfg_dict = {}
    train_run = checkpoint.get("train_run")
    if not isinstance(train_run, dict):
        train_run = {}
    tensorboard_meta = checkpoint.get("tensorboard")
    if not isinstance(tensorboard_meta, dict):
        tensorboard_meta = {}

    metadata: dict[str, Any] = {}
    if checkpoint_path:
        metadata["checkpoint"] = checkpoint_path
    epoch = checkpoint.get("epoch")
    if isinstance(epoch, int):
        metadata["epoch"] = epoch
    if test_data:
        metadata["test_data"] = test_data

    backbone = cfg_dict.get("backbone", "resnet18")
    if isinstance(backbone, str):
        metadata["backbone"] = backbone
    preset = cfg_dict.get("backbone_preset")
    if isinstance(preset, str) and preset:
        metadata["preset"] = preset
    scheduler = cfg_dict.get("scheduler")
    if isinstance(scheduler, str) and scheduler:
        metadata["scheduler"] = scheduler

    best_val_loss = checkpoint.get("best_val_loss", checkpoint.get("val_loss"))
    if isinstance(best_val_loss, (int, float)):
        metadata["best_val_loss"] = round(float(best_val_loss), 4)
    best_val_kp_error = checkpoint.get(
        "best_val_kp_error", checkpoint.get("val_kp_error")
    )
    if isinstance(best_val_kp_error, (int, float)):
        metadata["best_val_kp_error"] = round(float(best_val_kp_error), 4)

    outdir = train_run.get("outdir")
    if isinstance(outdir, str) and outdir:
        metadata["run"] = outdir
    resume_checkpoint = train_run.get("resume_checkpoint")
    if isinstance(resume_checkpoint, str) and resume_checkpoint:
        metadata["resumed_from"] = resume_checkpoint
    logdir = tensorboard_meta.get("logdir")
    if isinstance(logdir, str) and logdir:
        metadata["tensorboard"] = logdir

    if cfg is not None:
        metadata["eval_batch_size"] = cfg.batch_size
        metadata["eval_device"] = cfg.device

    if not metadata:
        return None
    return "eval metadata: " + json.dumps(metadata, sort_keys=True)


def format_kp_error_regression_alert(
    *,
    epoch: int,
    current_kp_error: float,
    previous_kp_error: float | None,
    best_kp_error: float | None,
    split_name: str = "val",
    tolerance: float = 1e-6,
) -> str | None:
    regressed_vs_previous = (
        previous_kp_error is not None
        and current_kp_error > previous_kp_error + tolerance
    )
    regressed_vs_best = (
        best_kp_error is not None and current_kp_error > best_kp_error + tolerance
    )
    if not regressed_vs_previous and not regressed_vs_best:
        return None

    parts = [
        f"alert: {split_name} kp_error regression at epoch {epoch:03d}",
        f"current={current_kp_error:.4f}",
    ]
    if regressed_vs_previous and previous_kp_error is not None:
        parts.append(f"previous={previous_kp_error:.4f}")
        parts.append(f"delta_prev=+{current_kp_error - previous_kp_error:.4f}")
    if regressed_vs_best and best_kp_error is not None:
        parts.append(f"best={best_kp_error:.4f}")
        parts.append(f"delta_best=+{current_kp_error - best_kp_error:.4f}")
    return " | ".join(parts)


# ----------------------------
# Train / eval loops
# ----------------------------
def train_one_epoch(
    model, dist_head, loader, opt, loss_hm, loss_dist, cfg: Config
) -> dict[str, Any]:
    model.train()
    dist_head.train()
    amp_device = "cuda" if cfg.device == "cuda" else "cpu"
    scaler = torch.GradScaler(amp_device, enabled=(cfg.device == "cuda"))

    tot = tot_hm = tot_d = tot_kp = 0.0
    n = 0
    example = None

    for batch in tqdm(loader, desc="train", leave=False):
        images = batch["image"].to(cfg.device)
        hm_tgt = batch["heatmaps"].to(cfg.device)
        conf = batch["conf"].to(cfg.device)
        valid = batch["valid"].to(cfg.device)
        y = batch["y"].to(cfg.device)

        opt.zero_grad(set_to_none=True)

        with torch.autocast(amp_device, enabled=(cfg.device == "cuda")):
            hm_pred = model(images)
            d_hat, _dbg = dist_head(hm_pred)

            L_hm = loss_hm(hm_pred, hm_tgt, conf, valid)
            L_d = loss_dist(d_hat, y)
            L = L_hm + cfg.lambda_dist * L_d

        kp_err = decoded_keypoint_error(hm_pred, hm_tgt, conf, valid, cfg)

        scaler.scale(L).backward()
        scaler.step(opt)
        scaler.update()

        if example is None:
            example = capture_tensorboard_example(
                images,
                hm_tgt,
                hm_pred,
                image_size=cfg.image_size,
                softargmax_beta=cfg.softargmax_beta,
            )

        tot += float(L.item())
        tot_hm += float(L_hm.item())
        tot_d += float(L_d.item())
        tot_kp += float(kp_err.item())
        n += 1

    return {
        "loss": tot / max(n, 1),
        "loss_hm": tot_hm / max(n, 1),
        "loss_dist": tot_d / max(n, 1),
        "kp_error": tot_kp / max(n, 1),
        "example": example,
    }


@torch.no_grad()
def eval_one_epoch(model, dist_head, loader, loss_hm, loss_dist, cfg: Config) -> dict:
    model.eval()
    dist_head.eval()
    tot = tot_hm = tot_d = tot_kp = 0.0
    n = 0
    example = None

    for batch in tqdm(loader, desc="eval", leave=False):
        images = batch["image"].to(cfg.device)
        hm_tgt = batch["heatmaps"].to(cfg.device)
        conf = batch["conf"].to(cfg.device)
        valid = batch["valid"].to(cfg.device)
        y = batch["y"].to(cfg.device)

        hm_pred = model(images)
        d_hat, _dbg = dist_head(hm_pred)

        if example is None:
            example = capture_tensorboard_example(
                images,
                hm_tgt,
                hm_pred,
                image_size=cfg.image_size,
                softargmax_beta=cfg.softargmax_beta,
            )

        L_hm = loss_hm(hm_pred, hm_tgt, conf, valid)
        L_d = loss_dist(d_hat, y)
        L = L_hm + cfg.lambda_dist * L_d
        kp_err = decoded_keypoint_error(hm_pred, hm_tgt, conf, valid, cfg)

        tot += float(L.item())
        tot_hm += float(L_hm.item())
        tot_d += float(L_d.item())
        tot_kp += float(kp_err.item())
        n += 1

    return {
        "loss": tot / max(n, 1),
        "loss_hm": tot_hm / max(n, 1),
        "loss_dist": tot_d / max(n, 1),
        "kp_error": tot_kp / max(n, 1),
        "example": example,
    }


# ----------------------------
# Main
# ----------------------------
def build_argument_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--mode",
        choices=["train", "test"],
        default="train",
        help="Train a new model or evaluate a checkpoint on held-out data",
    )
    ap.add_argument(
        "--train-data",
        "--train_json",
        dest="train_data",
        default=None,
        help="Training annotations (.csv from rodent_dataset.py) or legacy JSON list",
    )
    ap.add_argument(
        "--val-data",
        "--val_json",
        dest="val_data",
        default=None,
        help="Validation annotations (.csv) or legacy JSON list",
    )
    ap.add_argument(
        "--test-data",
        dest="test_data",
        default=None,
        help="Test annotations (.csv) or legacy JSON list used in --mode test",
    )
    ap.add_argument(
        "--template-data",
        "--template_json",
        dest="template_data",
        default=None,
        help="Template annotations (.csv with 1 row) or legacy JSON record",
    )
    ap.add_argument(
        "--checkpoint",
        default=None,
        help="Checkpoint path for --mode test",
    )
    ap.add_argument(
        "--resume-checkpoint",
        default=None,
        help="Checkpoint path to resume from in train mode",
    )
    ap.add_argument("--outdir", default=None)
    ap.add_argument("--epochs", type=int, default=None)
    ap.add_argument("--batch_size", type=int, default=None)
    ap.add_argument("--lr", type=float, default=None)
    ap.add_argument("--num_workers", type=int, default=None)
    ap.add_argument(
        "--scheduler",
        choices=["cosine", "none"],
        default=None,
        help="Learning-rate scheduler. When omitted, large-batch Swin2 runs auto-enable cosine decay; use 'none' to disable it explicitly",
    )
    ap.add_argument(
        "--warmup-epochs",
        type=int,
        default=None,
        help="Warmup epochs for the learning-rate scheduler",
    )
    ap.add_argument(
        "--warmup-start-factor",
        type=float,
        default=None,
        help="Starting LR multiplier used during warmup",
    )
    ap.add_argument(
        "--min-lr-ratio",
        type=float,
        default=None,
        help="Final LR as a fraction of the configured base LR for cosine decay",
    )
    ap.add_argument(
        "--early-stop-patience",
        type=int,
        default=None,
        help="Stop training after this many non-improving validation epochs",
    )
    ap.add_argument(
        "--backbone",
        default=None,
        help="Backbone name for training. Use 'resnet18' or a timm model like 'swinv2_cr_tiny_384'",
    )
    ap.add_argument(
        "--backbone-preset",
        choices=sorted(BACKBONE_PRESETS),
        default=None,
        help="Named preset for non-ResNet backbones. 'balanced' keeps the default tradeoff and 'accuracy' uses a deeper Swin2 feature stage",
    )
    ap.add_argument(
        "--pretrained",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Enable or disable pretrained backbone weights",
    )
    ap.add_argument(
        "--backbone-feature-index",
        type=int,
        default=None,
        help="Feature stage index to extract from timm backbones",
    )
    ap.add_argument(
        "--decoder-channels",
        type=int,
        default=None,
        help="Intermediate channel count in the heatmap decoder",
    )
    ap.add_argument(
        "--tensorboard-dir",
        default=None,
        help="Optional TensorBoard log directory. Defaults to <outdir>/tensorboard in train mode",
    )
    return ap


def run_train(args: argparse.Namespace) -> int:
    os.makedirs(args.outdir, exist_ok=True)

    if args.resume_checkpoint:
        (
            resume_checkpoint,
            cfg,
            model,
            dist_head,
            loss_hm,
            loss_dist,
            opt,
        ) = load_checkpoint_training_runtime(
            args.resume_checkpoint,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            num_workers=args.num_workers,
            scheduler=args.scheduler,
            warmup_epochs=args.warmup_epochs,
            warmup_start_factor=args.warmup_start_factor,
            min_lr_ratio=args.min_lr_ratio,
            early_stop_patience=args.early_stop_patience,
            backbone=args.backbone,
            backbone_preset=args.backbone_preset,
            pretrained=args.pretrained,
            backbone_feature_index=args.backbone_feature_index,
            decoder_channels=args.decoder_channels,
        )
        subset_mask = resume_checkpoint["subset_mask"].bool()
        kp_weight = resume_checkpoint["kp_weight"].float()
        template_Tn = resume_checkpoint["template_Tn"].float()
        start_epoch = int(resume_checkpoint.get("epoch", 0)) + 1
        best = float(
            resume_checkpoint.get(
                "best_val_loss", resume_checkpoint.get("val_loss", float("inf"))
            )
        )
        best_kp_error = float(
            resume_checkpoint.get(
                "best_val_kp_error",
                resume_checkpoint.get("val_kp_error", float("inf")),
            )
        )
        previous_eval_kp_error = resume_checkpoint.get("val_kp_error")
        if not isinstance(previous_eval_kp_error, (int, float)):
            previous_eval_kp_error = None
        raw_epochs_without_improvement = resume_checkpoint.get(
            "epochs_without_improvement", 0
        )
        if isinstance(raw_epochs_without_improvement, (int, float)):
            epochs_without_improvement = max(int(raw_epochs_without_improvement), 0)
        else:
            epochs_without_improvement = 0
    else:
        resume_checkpoint = None
        cfg = config_from_args(
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            num_workers=args.num_workers,
            scheduler=args.scheduler,
            warmup_epochs=args.warmup_epochs,
            warmup_start_factor=args.warmup_start_factor,
            min_lr_ratio=args.min_lr_ratio,
            early_stop_patience=args.early_stop_patience,
            backbone=args.backbone,
            backbone_preset=args.backbone_preset,
            pretrained=args.pretrained,
            backbone_feature_index=args.backbone_feature_index,
            decoder_channels=args.decoder_channels,
        )
        subset_mask, kp_weight = build_subset_and_weights(cfg)
        template_Tn = load_template_Tn(args.template_data, cfg)
        model, dist_head, loss_hm, loss_dist = build_runtime_components(
            cfg,
            template_Tn.to(cfg.device),
            subset_mask.to(cfg.device),
            kp_weight.to(cfg.device),
        )
        opt = torch.optim.AdamW(
            list(model.parameters()) + list(dist_head.parameters()),
            lr=cfg.lr,
            weight_decay=cfg.weight_decay,
        )
        start_epoch = 1
        best = float("inf")
        best_kp_error = float("inf")
        previous_eval_kp_error = None
        epochs_without_improvement = 0

    if cfg.early_stop_patience is not None and not args.val_data:
        raise ValueError("--val-data is required when early stopping is enabled")

    # Load items
    train_items, train_summary = load_frame_items_with_summary(args.train_data)
    print_frame_summary("train", train_summary)
    if not train_items:
        raise ValueError("No usable training rows were found in the training data")

    val_summary = None
    if args.val_data:
        val_items, val_summary = load_frame_items_with_summary(args.val_data)
        print_frame_summary("val", val_summary)
        if not val_items:
            raise ValueError(
                "No usable validation rows were found in the validation data"
            )
    else:
        val_items = None

    # Datasets / loaders
    train_loader = build_loader(
        train_items,
        template_Tn,
        subset_mask,
        kp_weight,
        cfg,
        shuffle=True,
        drop_last=True,
    )

    if val_items:
        val_loader = build_loader(
            val_items,
            template_Tn,
            subset_mask,
            kp_weight,
            cfg,
            shuffle=False,
            drop_last=False,
        )
    else:
        val_loader = None

    resolved_tensorboard_dir = resolve_resume_tensorboard_dir(
        args.tensorboard_dir,
        args.outdir,
        resume_checkpoint,
    )
    writer, tensorboard_dir = build_tensorboard_writer(
        args.outdir, resolved_tensorboard_dir
    )
    writer.add_text(
        "config/json", json.dumps(cfg.__dict__, sort_keys=True, indent=2), 0
    )
    if train_summary is not None:
        writer.add_text("data/train_summary", str(train_summary), 0)
    if val_summary is not None:
        writer.add_text("data/val_summary", str(val_summary), 0)
    if resume_checkpoint is not None:
        writer.add_text(
            "resume/checkpoint", str(args.resume_checkpoint), start_epoch - 1
        )
        writer.add_text(
            "resume/metadata",
            json.dumps(
                {
                    "start_epoch": start_epoch,
                    "best_val_loss": best,
                    "previous_logdir": resume_checkpoint.get("tensorboard", {}).get(
                        "logdir"
                    ),
                },
                sort_keys=True,
                indent=2,
            ),
            start_epoch - 1,
        )
    print(f"tensorboard logs: {tensorboard_dir}")
    print(
        f"optimizer: base_lr={cfg.lr:.2e} scheduler={cfg.scheduler or 'none'} "
        f"warmup_epochs={cfg.warmup_epochs} min_lr_ratio={cfg.min_lr_ratio:.3f}"
    )
    try:
        for epoch in range(start_epoch, cfg.epochs + 1):
            epoch_lr = learning_rate_for_epoch(cfg, epoch)
            set_optimizer_lr(opt, epoch_lr)
            tr = train_one_epoch(
                model, dist_head, train_loader, opt, loss_hm, loss_dist, cfg
            )

            if val_loader is not None:
                va = eval_one_epoch(
                    model, dist_head, val_loader, loss_hm, loss_dist, cfg
                )
            else:
                va = {
                    "loss": tr["loss"],
                    "loss_hm": tr["loss_hm"],
                    "loss_dist": tr["loss_dist"],
                    "kp_error": tr["kp_error"],
                }

            write_metrics_to_tensorboard(
                writer,
                epoch,
                train_metrics=tr,
                val_metrics=va,
                lr=epoch_lr,
            )
            write_example_artifacts_to_tensorboard(
                writer, epoch, "train", tr.get("example")
            )
            write_example_artifacts_to_tensorboard(
                writer, epoch, "val", va.get("example")
            )

            print(
                f"epoch {epoch:03d} | "
                f"train loss={tr['loss']:.4f} (hm={tr['loss_hm']:.4f}, dist={tr['loss_dist']:.4f}, kp={tr['kp_error']:.4f}) | "
                f"val loss={va['loss']:.4f} (hm={va['loss_hm']:.4f}, dist={va['loss_dist']:.4f}, kp={va['kp_error']:.4f})"
            )

            current_eval_kp_error = float(va["kp_error"])
            alert = format_kp_error_regression_alert(
                epoch=epoch,
                current_kp_error=current_eval_kp_error,
                previous_kp_error=previous_eval_kp_error,
                best_kp_error=(
                    None if not math.isfinite(best_kp_error) else best_kp_error
                ),
                split_name=("val" if val_loader is not None else "train"),
            )
            if alert is not None:
                print(alert)

            current_val_loss = float(va["loss"])
            improved = current_val_loss < best
            if improved:
                best = current_val_loss
                epochs_without_improvement = 0
            else:
                epochs_without_improvement += 1

            best_after_epoch = float(best)
            best_kp_error_after_epoch = min(best_kp_error, current_eval_kp_error)

            ckpt = {
                "epoch": epoch,
                "cfg": cfg.__dict__,
                "kp_order": BP,
                "subset_mask": subset_mask.cpu(),
                "kp_weight": kp_weight.cpu(),
                "template_Tn": template_Tn.cpu(),
                "model": model.state_dict(),
                "dist_head": dist_head.state_dict(),
                "opt": opt.state_dict(),
                "scheduler": scheduler_state_for_checkpoint(cfg, epoch, epoch_lr),
                "val_loss": current_val_loss,
                "val_kp_error": current_eval_kp_error,
                "best_val_loss": best_after_epoch,
                "best_val_kp_error": float(best_kp_error_after_epoch),
                "epochs_without_improvement": epochs_without_improvement,
                "tensorboard": {
                    "logdir": tensorboard_dir,
                    "last_epoch": epoch,
                },
                "train_run": {
                    "outdir": args.outdir,
                    "train_data": args.train_data,
                    "val_data": args.val_data,
                    "template_data": args.template_data,
                    "resume_checkpoint": args.resume_checkpoint,
                },
            }

            torch.save(ckpt, os.path.join(args.outdir, f"ckpt_epoch_{epoch:03d}.pt"))
            if improved:
                writer.add_scalar("best/val_loss", best, epoch)
                torch.save(ckpt, os.path.join(args.outdir, "best.pt"))
            if (
                cfg.early_stop_patience is not None
                and epochs_without_improvement >= cfg.early_stop_patience
            ):
                print(
                    f"early stopping at epoch {epoch:03d}: "
                    f"val_loss={current_val_loss:.4f} best_val_loss={best:.4f} "
                    f"patience={cfg.early_stop_patience}"
                )
                best_kp_error = best_kp_error_after_epoch
                previous_eval_kp_error = current_eval_kp_error
                break
            best_kp_error = best_kp_error_after_epoch
            previous_eval_kp_error = current_eval_kp_error
        writer.flush()
    finally:
        writer.close()

    print(f"done. best val loss = {best:.4f}")
    return 0


def run_test(args: argparse.Namespace) -> int:
    (
        checkpoint,
        cfg,
        model,
        dist_head,
        loss_hm,
        loss_dist,
    ) = load_checkpoint_runtime(
        args.checkpoint,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
    )
    provenance = format_checkpoint_provenance(checkpoint, args.checkpoint)
    if provenance is not None:
        print(provenance)
    eval_metadata = format_eval_metadata(
        checkpoint,
        checkpoint_path=args.checkpoint,
        test_data=args.test_data,
        cfg=cfg,
    )
    if eval_metadata is not None:
        print(eval_metadata)

    template_Tn = checkpoint["template_Tn"].float()
    subset_mask = checkpoint["subset_mask"].bool()
    kp_weight = checkpoint["kp_weight"].float()

    test_items, test_summary = load_frame_items_with_summary(args.test_data)
    print_frame_summary("test", test_summary)
    if not test_items:
        raise ValueError("No usable test rows were found in the test data")

    test_loader = build_loader(
        test_items,
        template_Tn,
        subset_mask,
        kp_weight,
        cfg,
        shuffle=False,
        drop_last=False,
    )
    metrics = eval_one_epoch(model, dist_head, test_loader, loss_hm, loss_dist, cfg)
    print(
        f"test loss={metrics['loss']:.4f} "
        f"(hm={metrics['loss_hm']:.4f}, dist={metrics['loss_dist']:.4f}, kp={metrics['kp_error']:.4f})"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = build_argument_parser()
    args = ap.parse_args(argv)

    if args.mode == "train":
        if not args.train_data:
            ap.error("--train-data is required in train mode")
        if not args.template_data and not args.resume_checkpoint:
            ap.error("--template-data is required in train mode")
        if not args.outdir:
            ap.error("--outdir is required in train mode")
        if args.early_stop_patience is not None and args.early_stop_patience < 1:
            ap.error("--early-stop-patience must be at least 1")
        if args.early_stop_patience is not None and not args.val_data:
            ap.error("--val-data is required when --early-stop-patience is set")
        if args.resume_checkpoint and not os.path.exists(args.resume_checkpoint):
            ap.error("--resume-checkpoint must point to an existing checkpoint")
        return run_train(args)

    if not args.test_data:
        ap.error("--test-data is required in test mode")
    if not args.checkpoint:
        ap.error("--checkpoint is required in test mode")
    return run_test(args)


if __name__ == "__main__":
    raise SystemExit(main())
